include: package:very_good_analysis/analysis_options.yaml

analyzer:
  strong-mode:
    implicit-casts: true
    implicit-dynamic: true

errors:
  close_sinks: ignore
  missing_required_param: error
  missing_return: error

linter:
  rules:
    public_member_api_docs: false
    sort_constructors_first: false
    lines_longer_than_80_chars: false
    omit_local_variable_types: false
    avoid_dynamic_calls: false