name: example_proj
description: A new Flutter project.


publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  auto_route: ^3.2.1
  beamer: ^1.3.0
  cupertino_icons: ^1.0.2
  dio: ^4.0.4
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.0.2
  flutter_loggy_dio: ^2.0.0+3
  flutter_secure_storage: ^5.0.2
  json_serializable: ^6.1.4
  loggy: ^2.0.1+1
  provider: ^6.0.2
  stacked: ^2.2.8
  

dev_dependencies:
  build_runner: ^2.1.7
  flutter_test:
    sdk: flutter
  very_good_analysis: ^2.4.0



flutter:
  uses-material-design: true

  assets:
    - .env

  fonts:
    - family: Commissioner
      fonts:
        - asset: assets/fonts/Commissioner/Commissioner-Bold.ttf
          weight: 700
        - asset: assets/fonts/Commissioner/Commissioner-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Commissioner/Commissioner-Medium.ttf
          weight: 500
        - asset: assets/fonts/Commissioner/Commissioner-Regular.ttf
          weight: 400
